[tox]
envlist =
    py38-django32
    py39-django32
    py310-django32
    py38-django42
    py39-django42
    py310-django42
    py311-django42
    py311-django50
    py312-django50
    py312-django51

[testenv]
deps =
    django32: django>=3.2,<4.0
    django42: django>=4.2,<5.0
    django50: django>=5.0,<5.1
    django51: django>=5.1,<5.2
    pytest
    pytest-django
    coverage
    Pillow>=10.0
    cairosvg>=2.7
    scour>=0.38.1
    blake3>=1.0
setenv =
    PYTHONPATH = {toxinidir}
    DJANGO_SETTINGS_MODULE = tests.settings
commands =
    pytest {posargs:tests/}

[gh-actions]
python =
    3.8: py38-django32, py38-django42
    3.9: py39-django32, py39-django42
    3.10: py310-django32, py310-django42
    3.11: py311-django42, py311-django50
    3.12: py312-django50, py312-django51
